#!/bin/bash

DATA="/data"
TARGETS=( "config.js" "content/data" "content/images" "content/themes" "content/apps" )

function link_if_exists
{
    if [[ -e "$DATA/$1" ]]; then
        rm -rf "$1"
        ln -s "$DATA/$1" "$1"
    fi
}

for target in ${TARGETS[@]}; do
    link_if_exists $target
done

npm start
